app/routes.py
from flask import Blueprint,current_app, render_template, request, redirect, url_for, session, flash
from .models import db, Election, Candidat, Electeur, Vote, Voix, Organisateur
from .services import count_vote
from datetime import datetime
import csv
import os


main = Blueprint('main', __name__)


# Login for Organisateurs and Electeurs
@main.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        user_type = request.form['user_type']  # Organisateur or Electeur
        
        print(user_type)
        if user_type == 'organisateur':
            cni = request.form['cni']
            password = request.form['password']
            
            if not cni or not password:
                print('CNI and password are required')
                return redirect(url_for('main.login'))
            
            # Login as Organisateur
            user = Organisateur.query.filter_by(cni=cni).first()
            if user:
                session['user_id'] = user.cni  # Store CNI in session
                session['role'] = 'organisateur'
                # return redirect(url_for('main.create_election'))
                return redirect(url_for('main.dashboard'))
            else:
                flash('Invalid credentials for Organisateur')

        elif user_type == 'electeur':
            cne = request.form['cne']
            
            if not cne:
                flash('CNE is required for Electeur')
                return redirect(url_for('main.login'))

            # Get the path to the CSV file in the project root
            csv_file_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'fichier_electoral.csv')

            # Login as Electeur
            cne_found = False
            with open(csv_file_path, newline='', encoding='ISO-8859-1') as csvfile:
                reader = csv.DictReader(csvfile)
                for row in reader:
                    if row['cne'] == cne:
                        cne_found = True
                        session['user_id'] = row['cne']  # Store CNE in session
                        session['role'] = 'electeur'
                        elc=Electeur(cne=cne,nom=row['nom'],prenom=row['prenom'])
                        existing_elc = Electeur.query.filter_by(cne=cne).first()
                        if existing_elc:
                            # User has already voted
                            return render_template('error.html', message="Il n'est permit de voter qu'une seule fois")   
                        db.session.add(elc)
                        db.session.commit()
                        return redirect(url_for('main.vote', election_id=row['election_id']))

            if not cne_found:
                flash('Invalid credentials for Electeur')

    # Clear only organisateur-specific session data
    session.pop('user_id', None)  # Assuming 'user_id' holds the organiser's session info
    session.pop('role', None)  # Remove the 'role' session
    return render_template('login.html')

# Dashboard
@main.route('/dashboard', methods=['GET', 'POST'])
def dashboard():
    election_id = 8
    nbre_candidats = Candidat.query.count()
    nbre_electeurs = Electeur.query.count()
    nbre_organisateurs = Organisateur.query.count()
    results = count_vote(election_id)
    return render_template('dashboard.html', 
    nbre_candidats=nbre_candidats, 
    nbre_electeurs=nbre_electeurs, 
    nbre_organisateurs=nbre_organisateurs,
    results=results)

# Electeurs
@main.route('/electeur', methods=['GET'])
def electeur():
    # Chemin du fichier CSV
    csv_file_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'fichier_electoral.csv')
    
    # Liste pour stocker les électeurs
    electeurs = []
    
    # Lire le fichier CSV
    with open(csv_file_path, newline='', encoding='ISO-8859-1') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            electeurs.append(row)  # Ajouter chaque électeur à la liste
    
    # Passer les données au template
    return render_template('electeur.html', electeurs=electeurs)

# Candidats
@main.route('/candidat', methods=['GET'])
def candidat():
    # Récupérer tous les candidats de la base de données 
    candidats = Candidat.query.all() 
    return render_template('candidat.html', candidats=candidats)



# Create an election
@main.route('/election/create', methods=['GET', 'POST'])
def create_election():
    if request.method == 'POST':
        titre = request.form['titre']
        date_heure_debut = request.form['date_debut']  # Updated to match the form field name
        date_heure_fin = request.form['date_fin']      # Updated to match the form field name
        modalites = request.form['modalites']
        organisateur_cni = request.form['organisateur_cni']  # Assuming CNI of Organisateur is provided
        
        # Fetch the Organisateur using the CNI
        organisateur = Organisateur.query.filter_by(cni=organisateur_cni).first()

        if not organisateur:
            flash('Organisateur not found')
            return redirect(url_for('main.create_election'))

        # Save to Election table
        election = Election(titre=titre, 
                            date_heure_debut=date_heure_debut, 
                            date_heure_fin=date_heure_fin, 
                            modalites=modalites)

        # Link the Organisateur to this election
        election.organisateur = organisateur

        db.session.add(election)
        db.session.commit()
        election = Election.query.filter_by(titre=titre).first()

        return redirect(url_for('main.create_candidate', election_id=election.id_election))
    
    return render_template('election_form.html')



# Create a candidate

@main.route('/candidat/create', methods=['GET', 'POST'])
def create_candidate():
    election_id = request.args.get('election_id')
    
    if request.method == 'POST':
        nom = request.form['nom']
        prenom = request.form['prenom']
        profession = request.form['profession']
        photo_file = request.files['photo']
        
        # Check if a file was uploaded
        if photo_file and photo_file.filename:
            # Ensure the filename is secure
            filename = photo_file.filename
            # Define the upload path
            upload_path = os.path.join(current_app.root_path, 'static/images', filename)
            # Save the file to the designated folder
            photo_file.save(upload_path)
            # Store the relative path to the image in the database
            photo_path = f'{filename}'
        else:
            photo_path = None  # Handle the case where no photo was uploaded
        
        # Save to Candidat table
        candidat = Candidat(nom=nom, prenom=prenom, profession=profession, 
                            photo=photo_path, election_id=election_id)
        db.session.add(candidat)
        db.session.commit()
        
        return redirect(url_for('main.create_candidate', election_id=election_id))
    
    return render_template('candidate_form.html', election_id=election_id)


# Register a voter
# @main.route('/electeur/register', methods=['GET', 'POST'])
# def register_electeur():
#     if request.method == 'POST':
#         cne = request.form['cne']
#         nom = request.form['nom']
#         prenom = request.form['prenom']
        
#         # Save to Electeur table
#         electeur = Electeur(cne=cne, nom=nom, prenom=prenom)
#         db.session.add(electeur)
#         db.session.commit()

#         return redirect(url_for('main.vote'))
#     return render_template('voter_form.html')

@main.route('/electeur/register', methods=['GET', 'POST'])
def register_electeur():
    if request.method == 'POST':
        # Récupérer les données du formulaire
        cne = request.form['cne']
        nom = request.form['nom']
        prenom = request.form['prenom']
        election_id = request.form['election_id']

        # Ajouter l'électeur à la base de données
        electeur = Electeur(cne=cne, nom=nom, prenom=prenom)
        db.session.add(electeur)
        db.session.commit()

        # Ajouter l'électeur au fichier CSV
        csv_file_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'fichier_electoral.csv')
        with open(csv_file_path, 'a', encoding='ISO-8859-1') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow([cne, nom, prenom, election_id])  # Assure-toi que l'ordre correspond aux colonnes du CSV

        # Rediriger vers la liste des électeurs avec un message de confirmation
        flash('Électeur ajouté avec succès')
        return redirect(url_for('main.electeur'))

    return render_template('voter_form.html')


# Voting route
@main.route('/vote', methods=['GET', 'POST'])
def vote():
    election_id = request.args.get('election_id')
    if request.method == 'POST':
        cne = request.form['cne']
        id_cnd_premier_choix = request.form['premier_choix']
        id_cnd_second_choix = request.form['second_choix']
        date_de_vote = datetime.now()
        
        # Save the vote to the Vote table
        vote = Vote(cne=cne, date_de_vote=date_de_vote, election_id=election_id)
        cnd_premier_choix= Candidat.query.filter_by(id_cnd=id_cnd_premier_choix).first()
        cnd_second_choix=Candidat.query.filter_by(id_cnd=id_cnd_second_choix).first()
        
        vote.cnd_premier_choix=cnd_premier_choix
        vote.cnd_second_choix=cnd_second_choix
        db.session.add(vote)
        db.session.commit()
         # After vote is processed, clear the session
        session.clear()  # This will remove all data from the session

        # Optionally, you can flash a message to confirm the user has voted
        flash('Thank you for voting. You have been logged out.')
        
        return redirect(url_for('main.login'))
    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <header>
        <img src="{{ url_for('static', filename='images/senegal.jfif') }}" alt="Logo" style="width: 50px; height: auto; margin-right: 10px; vertical-align: middle;">
        <h1>E-Vote</h1>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
</body>
</html>

app/templates/candidat.html
{% extends "base.html" %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
  <h2>LISTE DES CANDIDATS</h2>
  <form method="GET" action="{{ url_for('main.create_candidate',election_id=election_id) }}">
    <label for="election_id">ID Election:</label>
    <input type="number" id="election_id" name="election_id" required>
    <button type="submit">Ajouter un candidat</button>
  </form>
</div>

<table class="table caption-top">
    <thead>
      <tr>
        <th scope="col">CNE</th>
        <th scope="col">Prenom</th>
        <th scope="col">Nom</th>
        <th scope="col">Profession</th>
        <th scope="col">ID Election</th>
      </tr>
    </thead>
    <tbody>
      {% for candidat in candidats %}
      <tr>
        <td>{{ candidat.id_cnd }}</td>
        <td>{{ candidat.prenom }}</td>
        <td>{{ candidat.nom }}</td>
        <td>{{ candidat.profession }}</td>
        <td>{{ candidat.election_id }}</td>
      </tr>
      {% endfor %}
    </tbody>
</table>

<form method="GET" action="{{ url_for('main.dashboard') }}">
    <div style="text-align: center; margin-top: 20px;">
        <button type="submit">Retour</button>
    </div>
</form>
{% endblock %}

app/templates/candidate_form.html
{% extends "base.html" %}
{% block content %}
    <h2>ENREGISTRER UN CANDIDAT</h2>
    <form method="POST" enctype="multipart/form-data" style="margin-bottom: 20px;">
        <div style="margin-bottom: 10px;">
            <label for="nom">Nom:</label>
            <input type="text" name="nom" required style="width: 100%; padding: 5px;">
        </div>
        <div style="margin-bottom: 10px;">
            <label for="prenom">Prénom du Candidat:</label>
            <input type="text" name="prenom" required style="width: 100%; padding: 5px;">
        </div>
        <div style="margin-bottom: 10px;">
            <label for="photo">Photo:</label>
            <input type="file" name="photo" required style="width: 100%; padding: 5px;">
        </div>
        <div style="margin-bottom: 10px;">
            <label for="profession">Profession:</label>
            <input type="text" name="profession" required style="width: 100%; padding: 5px;">
        </div>
        <button type="submit" style="margin-top: 10px;">Créer</button>
    </form>


    <form method="GET" action="{{ url_for('main.dashboard') }}">
        <div style="text-align: center; margin-top: 20px;">
            <button type="submit">Accueil</button>
        </div>
    </form>

{% endblock %}

app/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

    <link rel="stylesheet" href="static/dashboard.css">
    <title>Dashboard</title>
</head>

<body>
    <div class="container">
        <div class="topbar">
            <div class="logo">
                <h2>E-Vote</h2>
            </div>
            <!-- <div class="search">
                <input type="text" name="search" placeholder="search here">
                <label for="search"><i class="fas fa-search"></i></label>
            </div> -->
            <!-- <i class="fas fa-bell"></i>
            <div class="user">
                <img src="img/user.png" alt="">
            </div> -->
        </div>
        <div class="sidebar">
            <ul>
                <li>
                    <a href="#">
                        <i class="fas fa-home"></i>
                        <div>Dashboard</div>
                    </a>
                </li>
                <li>
                    <a href="{{ url_for('main.create_election') }}">
                        <i class="fas fa-balance-scale"></i>
                        <div>Elections</div>
                    </a>
                </li>
                <li>
                    <a href="{{ url_for('main.candidat') }}">
                        <i class="fas fa-user-check"></i>
                        <div>Candidats</div>
                    </a>
                </li>
                <li>
                    <a href="{{ url_for('main.electeur') }}">
                        <i class="fas fa-users"></i>
                        <div>Electeurs</div>
                    </a>
                </li>
    
                <br><br>
                <li>
                    <a href="{{ url_for('main.login') }}">
                        
                        <i class="fas fa-sign-out-alt"></i>
                        <div>Deconnexion</div>
                    </a>
                </li> 
            </ul>
        </div>
        <div class="main">
            <div class="cards">
                <div class="card">
                    <div class="card-content">
                        <div class="number">{{nbre_candidats}}</div>
                        <div class="card-name">Candidats</div>
                    </div>
                    <div class="icon-box">
                        <i class="fas fa-user-check"></i>
                    </div>
                </div>
                <div class="card">
                    <div class="card-content">
                        <div class="number">{{nbre_electeurs}}</div>
                        <div class="card-name">Electeurs</div>
                    </div>
                    <div class="icon-box">
                        <i class="fas fa-users"></i>
                    </div>
                </div>
                <div class="card">
                    <div class="card-content">
                        <div class="number">{{ nbre_organisateurs }}</div>
                        <div class="card-name">Organisateurs</div>
                    </div>
                    <div class="icon-box">
                        <i class="fas fa-chalkboard-teacher"></i>
                    </div>
                    
                </div>
            </div>
            <h2><center>RESULTATS DE L'ELECTION</center></h2>
            <table>
                <thead>
                    <tr>
                        <th>Candidat</th>
                        <th>Total Voix</th>
                        <th>Pourcentage</th>
                        <th>Rang</th>
                    </tr>
                </thead>
                <tbody>
                    {% for voix in results %}
                    <tr>
                        <td>{{ voix.Candidat.nom }} {{ voix.Candidat.prenom }}</td>
                        <td>{{ voix.Voix.total_voix }}</td>
                        <td>{{ voix.Voix.pourcentage }}%</td>
                        <td>{{ voix.Voix.rang }}</td>
                    </tr>            
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.5.1/dist/chart.min.js"></script>
    <script src="static/chart1.js"></script>
    <script src="static/chart2.js"></script>
</body>

</html>

app/templates/electeur.html
{% extends "base.html" %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h2>LISTE DES ELECTEURS</h2>
    <!-- <a href="{{ url_for('main.register_electeur') }}" class="btn btn-success">Ajouter Électeur</a> -->
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">CNE</th>
            <th scope="col">Prénom</th>
            <th scope="col">Nom</th>
            <th scope="col">ID Election</th>
        </tr>
    </thead>
    <tbody>
        {% for electeur in electeurs %}
        <tr>
            <td>{{ electeur['cne'] }}</td>
            <td>{{ electeur['prenom'] }}</td>
            <td>{{ electeur['nom'] }}</td>
            <td>{{ electeur['election_id'] }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<form method="GET" action="{{ url_for('main.dashboard') }}">
    <div style="text-align: center; margin-top: 20px;">
        <button type="submit">Retour</button>
    </div>
</form>

{% endblock %}

app/templates/election_form.html
{% extends "base.html" %} {% block content %}
<h2>ORGANISER UNE ELECTION</h2>
<form method="POST" id="electionForm">
  <label for="titre">Titre:</label>
  <input type="text" name="titre" required /><br />
  <label for="organisateur_cni">CNI de l'organisateur</label>
  <input type="text" name="organisateur_cni" required /><br />
  <label for="date_debut">Date et Heure de Début:</label>
  <input type="datetime-local" name="date_debut" required /><br />
  <label for="date_fin">Date et Heure de Fin:</label>
  <input type="datetime-local" name="date_fin" required /><br />
  <label for="modalites">Modalités:</label>
  <textarea name="modalites" required></textarea><br />
  <button type="submit">Créer</button>
  <button type="button" onclick="document.getElementById('electionForm').reset();">Annuler</button>
</form>
{% endblock %}

app/templates/error.html
<!-- templates/error.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Un problème est survenu</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8d7da;
            color: #721c24;
            text-align: center;
            padding: 50px;
        }
        .error-container {
            padding: 20px;
            border-radius: 5px;
            background-color: #f2dede;
            border: 1px solid #ebccd1;
        }
    </style>
</head>
<body>
    <div class="error-container">
        <h1>Error</h1>
        <p>{{ message }}</p>
    </div>
</body>
</html>

app/templates/login.html
{% extends "base.html" %} {% block content %}
<div class="form-container">
  <h2 class="form-title">Sign in</h2>
  <form id="userForm" method="POST">
    <!-- Radio Buttons for Electeur and Organisateur -->
    <div class="radio-group">
      <div class="radio-label">
        <input type="radio" name="user_type" value="electeur" checked />
        <label>Electeur</label>
      </div>
      <div class="radio-label">
        <input type="radio" name="user_type" value="organisateur" />
        <label>Organisateur</label>
      </div>
    </div>

    <!-- Electeur Section -->
    <div id="electeurFields">
      <label for="cne">CNE:</label>
      <textarea name="cne"></textarea><br />
    </div>

    <!-- Organisateur Section -->
    <div id="organisateurFields" style="display: none">
      <label for="cni">CNI:</label>
      <input type="cni" name="cni" /><br />
      <!-- <textarea name="cni"></textarea><br /> -->
      <label for="email">Email:</label>
      <input type="email" name="email" /><br />
      <label for="password">Password:</label>
      <input type="password" name="password" /><br />
    </div>

    <button type="submit">Connexion</button>
  </form>
</div>

<!-- JavaScript to toggle fields -->
<script>
  const electeurFields = document.getElementById("electeurFields");
  const organisateurFields = document.getElementById("organisateurFields");

  document.querySelectorAll('input[name="user_type"]').forEach((radio) => {
    radio.addEventListener("change", function () {
      if (this.value === "electeur") {
        electeurFields.style.display = "block";
        organisateurFields.style.display = "none";
      } else {
        electeurFields.style.display = "none";
        organisateurFields.style.display = "block";
      }
    });
  });
</script>

{% endblock %}

app/templates/logintest.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>E-Vote | Connexion</title>
  <link rel="stylesheet" href="static/style.css">

</head>
<body>
<!-- partial:index.partial.html -->
<!DOCTYPE html>
<html>
<head>
	<title>Slide Navbar</title>
	<link rel="stylesheet" type="text/css" href="slide navbar style.css">
<link href="https://fonts.googleapis.com/css2?family=Jost:wght@500&display=swap" rel="stylesheet">
</head>
<body>
	<div class="main">  	
		<input type="checkbox" id="chk" aria-hidden="true">

			<div class="signup">
				<form>
					<label for="chk" aria-hidden="true">Sign up</label>
					<input type="text" name="txt" placeholder="User name" required="">
					<input type="email" name="email" placeholder="Email" required="">
					<input type="password" name="pswd" placeholder="Password" required="">
					<button>Sign up</button>
				</form>
			</div>

			<div class="login">
				<form>
					<label for="chk" aria-hidden="true">Login</label>
					<input type="text" name="email_or_cne" placeholder="Email or CNE" required="">
					<select name="user_type" required class="custom-select">
						<option value="" disabled selected>Select User Type</option>
						<option value="organisateur">Organisateur</option>
						<option value="electeur">Electeur</option>
					</select>
					
					<input type="password" name="password" placeholder="Password" required="">
					<button>Login</button>
				</form>
			</div>
	</div>
</body>
</html>
<!-- partial -->
  
</body>
</html>

app/templates/results.html
{% extends "base.html" %}
{% block content %}
    <h2>Résultats de l'Élection</h2>
    <table>
        <thead>
            <tr>
                <th>Candidat</th>
                <th>Total Voix</th>
                <th>Pourcentage</th>
                <th>Rang</th>
            </tr>
        </thead>
        <tbody>
            {% for voix in results %}
            <tr>
                <td>{{ voix.Candidat.nom }} {{ voix.Candidat.prenom }}</td>
                <td>{{ voix.Voix.total_voix }}</td>
                <td>{{ voix.Voix.pourcentage }}%</td>
                <td>{{ voix.Voix.rang }}</td>
            </tr>            
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/vote_form.html
{% extends "base.html" %} {% block content %}
<h2>Votez par ordre de préférences</h2>
<form method="POST" style="margin-bottom: 20px">
  <div style="margin-bottom: 10px">
    <label for="cne">CNE :</label>
    <input type="text" name="cne" required style="width: 100%; padding: 5px" />
  </div>

  <div style="margin-bottom: 20px">
    <label>Premier Choix:</label>
    <div id="first-choice" class="candidate-grid">
      {% for candidat in candidats %}
      <div
        class="candidate-card"
        onclick="selectCandidate('premier_choix', '{{ candidat.id_cnd }}')"
      >
        <input
          type="radio"
          name="premier_choix"
          id="first_{{ candidat.id_cnd }}"
          value="{{ candidat.id_cnd }}"
          style="display: none"
        />
        <label for="first_{{ candidat.id_cnd }}">
          <img
            src="{{ url_for('static', filename='images/' + candidat.photo) }}"
            alt="{{ candidat.nom }} {{ candidat.prenom }}"
            class="candidate-photo"
          />
          <p>{{ candidat.nom }} {{ candidat.prenom }}</p>
        </label>
      </div>
      {% endfor %}
    </div>
  </div>

  <div style="margin-bottom: 20px">
    <label>Second Choix:</label>
    <div id="second-choice" class="candidate-grid">
      {% for candidat in candidats %}
      <div
        class="candidate-card"
        id="second_{{ candidat.id_cnd }}"
        onclick="selectCandidate('second_choix', '{{ candidat.id_cnd }}')"
      >
        <input
          type="radio"
          name="second_choix"
          id="secondRadio_{{ candidat.id_cnd }}"
          value="{{ candidat.id_cnd }}"
          style="display: none"
        />
        <label for="secondRadio_{{ candidat.id_cnd }}">
          <img
            src="{{ url_for('static',filename='images/' + candidat.photo) }}"
            alt="{{ candidat.nom }} {{ candidat.prenom }}"
            class="candidate-photo"
          />
          <p>{{ candidat.nom }} {{ candidat.prenom }}</p>
        </label>
      </div>
      {% endfor %}
    </div>
  </div>

  <button type="submit" style="margin-top: 10px">Soumettre le Vote</button>
</form>

<form method="GET" action="{{ url_for('main.login') }}">
  <div style="text-align: center; margin-top: 20px">
    <button type="submit">Retour</button>
  </div>
</form>

<script>
  function selectCandidate(choice, id) {
    const selectedFirstChoice = document.querySelector(
      'input[name="premier_choix"]:checked'
    );

    if (choice === "premier_choix") {
      document
        .querySelectorAll("#second-choice .candidate-card")
        .forEach((card) => {
          card.style.display = "block";
        });

      if (selectedFirstChoice) {
        const selectedId = selectedFirstChoice.value;
        document.querySelector(`#second_${selectedId}`).style.display = "none";
      }
    }
  }
</script>

<style>
  .candidate-grid {
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
  }
  .candidate-card {
    border: 2px solid #ccc;
    border-radius: 8px;
    text-align: center;
    cursor: pointer;
    width: 120px;
    padding: 10px;
  }
  .candidate-photo {
    width: 80px;
    height: 80px;
    object-fit: cover;
    border-radius: 50%;
  }
  .candidate-card label {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    font-weight: bold;
  }
  .candidate-card input[type="radio"]:checked + label {
    border: 2px solid #299b63;
    color: #299b63;
  }
</style>
{% endblock %}

app/templates/voter_form.html
{% extends "base.html" %}
{% block content %}
<h2>AJOUTER UN ELECTEUR</h2>
<form method="POST">
    <div class="mb-3">
        <label for="cne" class="form-label">CNE</label>
        <input type="text" class="form-control" id="cne" name="cne" required>
    </div>
    <div class="mb-3">
        <label for="nom" class="form-label">Nom</label>
        <input type="text" class="form-control" id="nom" name="nom" required>
    </div>
    <div class="mb-3">
        <label for="prenom" class="form-label">Prénom</label>
        <input type="text" class="form-control" id="prenom" name="prenom" required>
    </div>
    <div class="mb-3">
        <label for="election_id" class="form-label">Election ID</label>
        <input type="text" class="form-control" id="election_id" name="election_id" required>
    </div>
    <button type="submit" class="btn btn-primary">Ajouter Électeur</button>
</form>
{% endblock %}